### ISSUE TITLE
Activating extension `EditorConfig.EditorConfig` failed: command with id already exists.

### ISSUE THREAD

**Issue by sean-mcmanus** [editorconfig/editorconfig#274]
I get this error when debugging our C/C++ extensions when the EditorConfig for VS Code extension is installed.

Activating extension `EditorConfig.EditorConfig` failed: command with id already exists.
Activating extension `EditorConfig.EditorConfig` failed:  command with id already exists
Here is the error stack:  Error: command with id already exists
    at t.registerCommand (f:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:11:3703)
    at Object.I.commands.registerCommand (f:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:12:28812)
    at activate (C:\Users\seanmcm\.vscode\extensions\EditorConfig.EditorConfig-0.3.3\out\src\editorConfigMain.js:11:23)
    at Function.t._callActivateOptional (f:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:12:22251)
    at Function.t._callActivate (f:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:12:22034)
    at f:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:12:21906
    at Object.m [as _notify] (f:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:5:19713)
    at Object.W.enter (f:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:5:23291)
    at n.Class.define._run (f:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:5:25119)
    at n.Class.define._completed (f:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:5:24560)
    at n.Class.derive.join.c (f:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:5:28098)
    at n.Class.derive.join.i.forEach.G.then.o.(anonymous function) (f:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:5:28315)
    at Object.m [as _notify] (f:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:5:19713)
    at Object.W.enter (f:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:5:23291)
    at n.Class.define._run (f:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:5:25119)
    at n.Class.define._completed (f:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:5:24560)
    at e.resolveOk (f:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:8:419)
    at p (f:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:7:30911)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by bsed** [comment]
Activating extension `chrisdias.vscodeEditorConfig` failed: command with id already exists.

**Comment by cxw42** [comment]
I am closing this issue as stale.  If you're still experiencing the problem, please reopen and post instructions for reproducing it.  Thanks!
