### ISSUE TITLE
Py core: numeric ranges don't handle zero correctly

### ISSUE THREAD

**Issue by cxw42** [editorconfig/editorconfig#371]
I am a relatively new user of editorconfig and have run across something strange.  In the Python core, the filename `foo0.txt` does not match the glob `foo{-10..10}.txt`.  However, [the Web page](https://editorconfig.org/#wildcards) suggests it should:

> `{num1..num2}` Matches any integer numbers between num1 and num2, where num1 and num2 can be either positive or negative.

### Test cases 

Tested on Cygwin x64 with [commit d1b3dd3 of editorconfig-core-py](https://github.com/editorconfig/editorconfig-core-py/commit/d1b3dd3206568b3d6d942ef3c9a9a115dda2383b).

    $ python
    Python 2.7.14 (default, Oct 31 2017, 21:12:13)
    [GCC 6.4.0] on cygwin
    >>> from editorconfig.fnmatch import *
    >>> fnmatchcase('foo0.txt','foo{-10..10}.txt')
    False

Oops!

    >>> fnmatchcase('foo1.txt','foo{-10..10}.txt')
    True

This one's OK.

    $ python3
    Python 3.6.4 (default, Jan  7 2018, 15:53:53)
    [GCC 6.4.0] on cygwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from editorconfig.fnmatch import *
    >>> fnmatchcase('foo0.txt','foo{-10..10}.txt')
    False

Same "oops" as above.

    >>> fnmatchcase('foo1.txt','foo{-10..10}.txt')
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "editorconfig-core-py/editorconfig/fnmatch.py", line 107, in fnmatchcase
        for (num, (min_num, max_num)) in zip(match.groups(), num_groups):
    ValueError: not enough values to unpack (expected 2, got 0)

Double oops!

### Thoughts

At least for Py 2, this seems to be related to [this](https://github.com/editorconfig/editorconfig-core-py/blob/60687c054bbaf4a8a1de5d8399910c0fbe367a7f/editorconfig/fnmatch.py#L108), which has an explicit test `== '0'`.  That was part of the [commit adding numeric-range support](https://github.com/editorconfig/editorconfig-core-py/commit/926d415a2bb3a929a3ae9aeadf81d73cebfc5dc9).

I have read the contributing guidelines and the code of conduct.  Thanks for looking into this!

**Comment by xuhdev** [comment]
Thank you for your suggestion and we really appreciate it.

This is a format change. If we want to make it into a standard, we have to initiate a vote, as the EditorConfig project espouses a relatively more democratic administration process rather than having one person dictating everything. If it got passed, all core libraries should be updated to support it. However, if it did not get passed, I don't think we would put such feature in any official core libraries -- we would like to avoid the situation in which some support it and some don't.

I like the fact that you have written up a fair amount of justification. Would you like to say more to increase the chance to pass before we start voting to get it more likely to pass? I would remain neural before the voting starts.

**Comment by cxw42** [comment]
@xuhdev Thank you for being willing to put this to a vote!  I will summarize:

### Problem

- At present, filename `060` is not matched by `{0..120}` in an editorconfig file.
- The [specification](https://editorconfig.org/#wildcards) says that

    > `{num1..num2}` matches any integer numbers between num1 and num2, where num1 and num2 can be either positive or negative

- I believe the behaviour is inconsistent with the specification: `060` is an integer number, but is not matched even though 0 < 60 < 120.

- Related: the pattern `{-10..10}` does not accept `0`, even though it does accept `+0` and `-0`.

### History

- This appears to originate from https://github.com/editorconfig/editorconfig-core-test/pull/1#commitcomment-6773978 , which references zsh behaviour.
- I just tried zsh, and it does accept `060` as part of the _range expression_ `<0-120>` ([reference](http://zsh.sourceforge.net/Doc/Release/Expansion.html#Glob-Operators)):

      zsh $ setopt extendedglob
      zsh $ setopt interactivecomments
      zsh $ [[ '60' == <0-120> ]] && echo yes       # No surprise here
      yes
      zsh $ [[ '060' == <0-120> ]] && echo yes      # <== The test case of interest
      yes
      zsh $ zsh --version
      zsh 5.5.1 (x86_64-unknown-cygwin)
 
  Note that range expressions `<n-m>` are different from [brace expansions](http://zsh.sourceforge.net/Doc/Release/Expansion.html#Brace-Expansion) `{n..m}`.  

### Proposal

I propose updating the documentation, test suite, and all cores so that:

- Leading zeroes on any number are permitted and ignored for purposes of matching.
  - For example, `{3..120}` will accept `60`, `060`, `0060`, ...

- `+0` and `-0` are accepted by any range accepting `0`.
  - For example, `{-10..10}` will accept `-1`, `-0`, `0`, `+0`, `+1`, `1`, ...

- Leading `+` is permitted on any positive number (it currently is, but the documentation doesn't expressly say so).
  - For example, `{0..10}` will accept `5` and `+5`.

- All numbers are treated as base 10, regardless of leading zeroes
  - For example, `60` and `060` will be the same number.
  - This permits using leading zeroes, e.g., as generated by imagemagick or zsh.  Zsh example:

        zsh $ echo {01..10}
        01 02 03 04 05 06 07 08 09 10

### Implementation notes

- In the Python and Vimscript cores, this is actually a matter of removing code rather than adding it!
- Generally speaking, these changes make number handling more consistent.  Therefore, I think it should be relatively easy to add them to the other cores.
- I am happy to assist with core, test, and documentation PRs.

Thank you all for considering this proposal!  I look forward to the core team's decision.  If you would like any other information or have any questions or comments, please let me know.  Much appreciated!

**Comment by rakus** [comment]
I just came here to propose the support of leading zeros, so I support Chris proposal.

The only thing I'm not certain is the support of `+`.

If I define a glob pattern `numbered-{0-9}.txt`, I would _not_ expect that `numbered-+0.txt or `numbered-+7.txt` are matched.

**Comment by rakus** [comment]
Another point is the ordering of then numbers. 
```
{numA...numB}
```
Has `numA` to be smaller than `numB`?

Personally I would propose NO. 

I tested ksh and bash and they both don't care about the ordering.

**Comment by rakus** [comment]
As globbing is influenced by Unix shell globbing, I thought I look what different shells do. Unfortunately they act different :-(.  I thought I collect the different outputs as a base for further discussion.

The following table is created via script. I attach the script for verification. (I had to add the extension `.txt`).

\#  | NumRange | bash | zsh | ksh 
---|----------|----------|----------|----------
  1 | `{1..7}` | `1 2 3 4 5 6 7` | `1 2 3 4 5 6 7` | `1 2 3 4 5 6 7` 
  2 | `{7..11}` | `7 8 9 10 11` | `7 8 9 10 11` | `7 8 9 10 11` 
  3 | `{-5..-1}` | `-5 -4 -3 -2 -1` | `-5 -4 -3 -2 -1` | `-5 -4 -3 -2 -1` 
  4 | `{-1..-5}` | `-1 -2 -3 -4 -5` | `-1 -2 -3 -4 -5` | `-1 -2 -3 -4 -5` 
  5 | `{+1..+5}` | `1 2 3 4 5` | `{+1..+5}` | `1 2 3 4 5` 
  6 | `{1..+5}` | `1 2 3 4 5` | `{1..+5}` | `1 2 3 4 5` 
  7 | `{01..07}` | `01 02 03 04 05 06 07` | `01 02 03 04 05 06 07` | `1 2 3 4 5 6 7` 
  8 | `{07..11}` | `07 08 09 10 11` | `07 08 09 10 11` | `7 8 9 10 11` 
  9 | `{07..011}` | `007 008 009 010 011` | `07 08 09 10 11` | `7 8 9` 
 10 | `{-05..-1}` | `-05 -04 -03 -02 -01` | `-05 -04 -03 -02 -01` | `-5 -4 -3 -2 -1` 
 11 | `{-05..-01}` | `-05 -04 -03 -02 -01` | `-05 -04 -03 -02 -01` | `-5 -4 -3 -2 -1` 
 12 | `{-05..01}` | `-05 -04 -03 -02 -01 000 001` | `-05 -04 -03 -02 -01 000 001` | `-5 -4 -3 -2 -1 0 1` 
 13 | `{-05..+01}` | `-05 -04 -03 -02 -01 000 001` | `{-05..+01}` | `-5 -4 -3 -2 -1 0 1` 
 14 | `{-01..-5}` | `-01 -02 -03 -04 -05` | `-01 -02 -03 -04 -05` | `-1 -2 -3 -4 -5` 
 15 | `{1..101}` | `1 2 3 ... 99 100 101` | `1 2 3 ... 99 100 101` | `1 2 3 ... 99 100 101` 
 16 | `{01..101}` | `001 002 003 ... 099 100 101` | `01 02 03 ... 99 100 101` | `1 2 3 ... 99 100 101` 
 17 | `{001..101}` | `001 002 003 ... 099 100 101` | `001 002 003 ... 099 100 101` | `1 2 3 ... 99 100 101` 
 18 | `{-1..101}` | `-1 0 1 ... 99 100 101` | `-1 0 1 ... 99 100 101` | `-1 0 1 ... 99 100 101` 
 19 | `{-01..101}` | `-01 000 001 ... 099 100 101` | `-01 000 001 ... 099 100 101` | `-1 0 1 ... 99 100 101` 
 20 | `{-001..101}` | `-001 0000 0001 ... 0099 0100 0101` | `-001 0000 0001 ... 0099 0100 0101` | `-1 0 1 ... 99 100 101` 

A few things to note:
- ksh interprets numbers with leading zeros as octal (see 9)
- zsh doesn't like a `+` in the num-range (5, 6, 13)
- no shell would match a leading `+`
- if the shell formats the number with leading zeros, the minus (`-`) acts the first leading zero (e.g. 20)

[test-num-ranges.sh.txt](https://github.com/editorconfig/editorconfig/files/3135450/test-num-ranges.sh.txt)
.

**Comment by rakus** [comment]
I didn't want to "pollute" my previous posts with opinions, as it should be just collected facts.

So here is the opinion part.

From the collected shell output I would lean to the bash implementation.

I propose the following definition:

**Expression**

- Base format regex: `{[-+]?[0-9]+\.\.[-+]?[0-9]+}` (as-is)
- Numbers are interpreted as decimal.
- The `+` is optional for positive numbers.
- It is irrelevant which of the numbers is greater or smaller. So `{1..9}` is equivalent to `{9..1}`.

**Matching**

- Positive numbers are matched without `+`. So `{0..3}` does **not** match `+2`.
- Zero (`0`) is matched without sign. So `{-1..2}` is equivalent to `{-1,0,1,2}`.
- If one of the numbers start with a leading zero (for negative numbers: after the `-`), all numbers are formatted with equal width, padding with leading zeros as needed. For negative numbers, the `-` is included when calculating the width.
  So:

    - `{1..03}` is equivalent to `{01,02,03}`
    - `{1..003}` is equivalent to `{001,002,003}`
    - `{01..003}` is equivalent to `{001,002,003}`
    - `{001..003}` is equivalent to `{001,002,003}`
    - `{-1..03}` is equivalent to `{-1,00,01,02,03}`
    - `{-01..3}` is equivalent to `{-01,000,001,002,003}`


**Special Cases**

If number ranges are used at all, I would expect something like `data-{000..999}.txt`. So I guess the following cases are rare or even extremely rare:

If you want to match `{-1,00,01,02,03,04,05,06,07,08,09,10}` you need the following expression `{{-1..09},10}`.

If you want to match positive numbers with or without `+`, you would need `{+,}{1..3}`. This would e.g. match `2`, but also `+2`.

If you explicitly want to match positive number with or without `+` `{-2,-1,-0,0,+0,1,+1,2,+2,3,+3}` you would need `{{-2..-1},[-+]0,{0..3},+{1..3}}`.

**Comment by xuhdev** [comment]
I would put this on onto voting after I add some basic structure to https://github.com/editorconfig/specification in the next few days.

**Comment by rakus** [comment]
Let me try to summarize:

1. Keep current implementation

- Don't allow leading zeros
- Match `+` on positive numbers. So `{1..3}` is equivalent to `{1,+1,2,+2,3,+3}`
- Matches sign on `0`. So `{-1..1}` is equivalent to `{-1,-0,0,+0,1,+1}`

2. Allow any number of leading zeros

- Allow any number of leading zeros.  So `{1..3}` matches `3` or `03` or `000003`.
- Handle `+` and `-` like the current implementation.

3. Implement leading zeros like bash

- Format all numbers to equal width, if one number contains a leading zero.
    - Determine width from longest number
    - A `-` sign is part of the width calculation.
    - E.g. `{1..03}` is equivalent to `{01,02,03}`
    - E.g. `{-1..01}` is equivalent to  `{-1,00,01}`
    - E.g. `{1..003}` is equivalent to  `{001,002,003}`
- Does _not_ match `+` on positive numbers. So `{1..3}` is equivalent to `{1,2,3}`
- Does _not_ match a sign on `0`. So `{-1..1}` is equivalent to `{-1,0,1}`


Independent from the proposals above: 

- The order of the number should be irrelevant. So `{1..3}` is equivalent to `{3..1}`.
- All numbers are treated as base 10, regardless of leading zeroes.

@cxw42: Do you agree with this summary?

**Comment by ffes** [comment]
Great summary to use in the specs :+1:

**Comment by cxw42** [comment]
@rakus thanks for the tests and summary!  I would like to think a bit more about syntax extensibility and numbers as numeric values vs. specific textual representations.  I am home sick today with a cold and will follow up once I am feeling better.

**Comment by rakus** [comment]
I'm a skeptical regarding "numbers as numeric values vs.  specific textual representations" .  
For a shell the brace expansion "is strictly textual" (bash man page, section "Brace Expansion").

**Comment by rakus** [comment]
@cxw42 Chris, you wanted to follow up on this issue. You input is needed, so we can go on with it. Especially important as the new specification efforts started in [editorconfig/specification](https://github.com/editorconfig/specification).

**Comment by cxw42** [comment]
@rakus Thanks for your patience!

## Brace expansion vs. range expressions

- Brace expansion answers the question "what numbers match this pattern?"  E.g., `{01..03}` => `01 02 03`.
- `zsh` range expressions answer the question "does *a particular number* match this pattern?"  E.g., `<1-3>` is matched by `1`, `01`, `001`, ... .

I believe sections in `.editorconfig` are closer to the second question.  Given a file the user wants to edit, the plugin has to answer the question "does the name of this file match this pattern?"  However, I recognize that the typical use cases of brace expansion are the first, not hte second.

## What to do about the current brace-expansion syntax?

The specification already has brace-expansion syntax, and we are trying to clarify it.  As far as I can tell, `bash` is the most widely used shell (e.g., survey [here](https://opensource.com/business/16/3/top-linux-shells)).  I therefore agree with following bash's syntax for [sequence expressions](https://www.gnu.org/software/bash/manual/html_node/Brace-Expansion.html), as documented by @rakus above at https://github.com/editorconfig/editorconfig/issues/371#issuecomment-488679604 .  I also recommend eventually supporting nonunity increments, for consistency with bash.  For the record, I quote bash's definition in full here:

> A sequence expression takes the form `{x..y[..incr]}`, where `x` and `y` are either integers or single characters, and `incr`, an optional increment, is an integer. When integers are supplied, the expression expands to each number between `x` and `y`, inclusive. 

I agree with expressly stating that the numbers are base 10.

> Supplied integers may be prefixed with ‘0’ to force each term to have the same width. When either `x` or `y` begins with a zero, the shell attempts to force all generated terms to contain the same number of digits, zero-padding where necessary.

I am leaving out the letter-increment part since that is not pertinent to this issue.

> When the increment is supplied, it is used as the difference between each term. The default increment is 1 or -1 as appropriate.

## Should we support range expressions?

I have opened #397 proposing that we do so using different syntax.  This provides an alternative for the "Special cases" section in https://github.com/editorconfig/editorconfig/issues/371#issuecomment-488679604 .  Just to provide a spoiler :) , those would be:

- To match `{-1,00,01,02,03,04,05,06,07,08,09,10}`: instead of `{{-1..09},10}`, `<#-1..10>` (although the former would certainly still work)

- To match positive numbers with or without `+`: instead of `{+,}{1..3}`, `<#1..3>`.

- To match positive number with or without `+` `{-2,-1,-0,0,+0,1,+1,2,+2,3,+3}`: instead of `{{-2..-1},[-+]0,{0..3},+{1..3}}`, `<#-2..3>`.

**Comment by rakus** [comment]
I commented and recommended some changes to the handling of numeric ranges, as I think that the current implementation is not very useful. If I use numbers in file names it would be most likely something with a fixed width number with leading zeros. E.g. `appl-001.log`, `appl-002.log` ...

Because of this I proposed to implement the number ranges similar to what bash does.

The interesting question is: Is it useful at all?

I'm not sure. I would be surprised to find a `.editorconfig` file that uses a numeric range expression. According to the Github Code search API, there are more than 5M files named `.editorconfig`. So there is a chance that someone uses numerical ranges, but I would still be surprised.

Assuming that numerical ranges were not part of editorconfig, I don't think I would recommend to add it.

But as numeric ranges are part of the editorconfig specification, they should be defined in a way that could be useful. Hence the proposal for bash-like behavior.

On the other hand, I would not recommend to add more complexity to it.  Different increments are useful for shell scripting (`for x in {2..8..2}; do ...`) but I can't imagine a use case in the context of editorconfig.

**Comment by cxw42** [comment]
@rakus Fair point on the use case - let's not worry about `incr`, then.
