### ISSUE TITLE
panic: key-value delimiter not found: View

### ISSUE THREAD

**Issue by billxinli** [editorconfig/editorconfig#390]
I am seeing the following errors when running `editorconfig`

My `.editorconfig` has:

```
root = true

[*]
charset = utf-8
end_of_line = lf
indent_size = 2
indent_style = space
insert_final_newline = true
trim_trailing_whitespace = true

[*.md]
trim_trailing_whitespace = false

[*.{iml,xml}]
insert_final_newline = false
```

```
npx editorconfig-checker .
panic: key-value delimiter not found: View


goroutine 1 [running]:

main.validateFile(0xc000193b90, 0x69, 0xc000153e00, 0x0, 0x0, 0x0)
	/home/maex/go/src/github.com/editorconfig-checker/editorconfig-checker/cmd/editorconfig-checker/main.go:203 +0x13da
main.processValidation(0xc00054a000, 0x4305, 0x4c00, 0x4c00, 0xc000110040, 0x37, 0x0)
	/home/maex/go/src/github.com/editorconfig-checker/editorconfig-checker/cmd/editorconfig-checker/main.go:269 +0xd3
main.main()
	/home/maex/go/src/github.com/editorconfig-checker/editorconfig-checker/cmd/editorconfig-checker/main.go:326 +0x9a
```

Curious what the issue might be.

**Comment by xuhdev** [comment]
Can you report this issue at https://github.com/editorconfig/editorconfig-core-go/issues
