### ISSUE TITLE
Atom Install Error

### ISSUE THREAD

**Issue by skadevz** [editorconfig/editorconfig#396]
$ apm install editorconfig 
Installing editorconfig to /home/skadevz/.atom/packages ✗

npm ERR! Unexpected end of JSON input while parsing near '...:"^2.7.1"},"_hasShrin'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/skadevz/.atom/.apm/_logs/2019-05-06T12_04_38_354Z-debug.log

> 0 info it worked if it ends with ok
1 verbose cli [ '/usr/share/atom/resources/app/apm/bin/node',
1 verbose cli   '/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js',
1 verbose cli   '--globalconfig',
1 verbose cli   '/home/skadevz/.atom/.apm/.apmrc',
1 verbose cli   '--userconfig',
1 verbose cli   '/home/skadevz/.atom/.apmrc',
1 verbose cli   'install',
1 verbose cli   'https://www.atom.io/api/packages/editorconfig/versions/2.4.0/tarball',
1 verbose cli   '--runtime=electron',
1 verbose cli   '--target=2.0.18',
1 verbose cli   '--dist-url=https://atom.io/download/electron',
1 verbose cli   '--arch=x64',
1 verbose cli   '--global-style' ]
2 info using npm@6.2.0
3 info using node@v8.9.3
4 verbose npm-session 77dda28533a87a1e
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://www.atom.io/api/packages/editorconfig/versions/2.4.0/tarball 3904ms
8 silly pacote remote manifest for undefined@https://www.atom.io/api/packages/editorconfig/versions/2.4.0/tarball fetched in 3995ms
9 timing stage:loadCurrentTree Completed in 4939ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 2ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule editorconfig@2.4.0 checking installable status
17 http fetch GET 304 https://registry.npmjs.org/pify 331ms (from cache)
18 http fetch GET 304 https://registry.npmjs.org/import-lazy 348ms (from cache)
19 http fetch GET 304 https://registry.npmjs.org/editorconfig 360ms (from cache)
20 silly pacote range manifest for editorconfig@^0.13.2 fetched in 388ms
21 silly resolveWithNewModule editorconfig@0.13.3 checking installable status
22 silly pacote range manifest for import-lazy@^2.1.0 fetched in 384ms
23 silly resolveWithNewModule import-lazy@2.1.0 checking installable status
24 silly pacote range manifest for pify@^2.3.0 fetched in 415ms
25 silly resolveWithNewModule pify@2.3.0 checking installable status
26 http fetch GET 304 https://registry.npmjs.org/commander 199ms (from cache)
27 silly fetchPackageMetaData error for commander@^2.9.0 Unexpected end of JSON input while parsing near '...:"^2.7.1"},"_hasShrin'
28 http fetch GET 304 https://registry.npmjs.org/sigmund 239ms (from cache)
29 silly pacote range manifest for sigmund@^1.0.1 fetched in 242ms
30 silly resolveWithNewModule sigmund@1.0.1 checking installable status
31 http fetch GET 304 https://registry.npmjs.org/semver 246ms (from cache)
32 silly pacote range manifest for semver@^5.1.0 fetched in 317ms
33 silly resolveWithNewModule semver@5.7.0 checking installable status
34 http fetch GET 304 https://registry.npmjs.org/lru-cache 363ms (from cache)
35 silly pacote range manifest for lru-cache@^3.2.0 fetched in 393ms
36 silly resolveWithNewModule lru-cache@3.2.0 checking installable status
37 http fetch GET 304 https://registry.npmjs.org/bluebird 424ms (from cache)
38 silly pacote range manifest for bluebird@^3.0.5 fetched in 454ms
39 silly resolveWithNewModule bluebird@3.5.4 checking installable status
40 timing stage:rollbackFailedOptional Completed in 2ms
41 timing stage:runTopLevelLifecycles Completed in 5854ms
42 silly saveTree apm-install-dir-11946-27413-f9dl2e.2svfg
42 silly saveTree └─┬ editorconfig@2.4.0
42 silly saveTree   ├── import-lazy@2.1.0
42 silly saveTree   └── pify@2.3.0
43 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...:"^2.7.1"},"_hasShrin'
43 verbose stack     at JSON.parse (<anonymous>)
43 verbose stack     at parseJson (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/json-parse-better-errors/index.js:7:17)
43 verbose stack     at consumeBody.call.then.buffer (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-fetch-npm/src/body.js:96:50)
43 verbose stack     at <anonymous>
43 verbose stack     at process._tickCallback (internal/process/next_tick.js:188:7)
44 verbose cwd /tmp/apm-install-dir-11946-27413-f9dl2e.2svfg
45 verbose Linux 4.15.0-48-generic
46 verbose argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/skadevz/.atom/.apm/.apmrc" "--userconfig" "/home/skadevz/.atom/.apmrc" "install" "https://www.atom.io/api/packages/editorconfig/versions/2.4.0/tarball" "--runtime=electron" "--target=2.0.18" "--dist-url=https://atom.io/download/electron" "--arch=x64" "--global-style"
47 verbose node v8.9.3
48 verbose npm  v6.2.0
49 error Unexpected end of JSON input while parsing near '...:"^2.7.1"},"_hasShrin'
50 verbose exit [ 1, true ]

apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.36.1
python 2.7.15rc1
git 2.17.1

I didn't use proxy, the internet connection is stable.
How to fix it?

**Comment by skadevz** [comment]
Solved by clearing the cache.
